version: '1.0'

services:

  postgres:
    image: postgres:16
    container_name: t1_java_demo
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1