GET http://localhost:8080/transactions

####

GET http://localhost:8080/transactions/15

###

POST http://localhost:8080/transactions
Content-Type: application/json

{
  "account_id": 1,
  "amount": 500.00
}

###

PUT http://localhost:8080/transactions/1
Content-Type: application/json

{
  "account_id": 1,
  "amount": 1600
}

###

DELETE http://localhost:8080/transactions/82

###

GET http://localhost:8080/accounts

###

GET http://localhost:8080/accounts/1

###

POST http://localhost:8080/accounts
Content-Type: application/json

{
  "account_type": "DEBIT",
  "client_id": 1,
  "balance": 300
}

###

PUT http://localhost:8080/accounts/1
Content-Type: application/json

{
  "client_id": 5,
  "account_type": "DEBIT",
  "balance": 100
}

###

DELETE http://localhost:8080/accounts/27

