spring:
  application:
    name: t1-java-demo
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: bestuser
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml
logging:
  level:
    ROOT: INFO
    ru.t1.java.demo.controller.ClientController: DEBUG

t1:
  kafka:
    bootstrap-server: ${KAFKA_SERVER:localhost:29092}
    consumer:
      group-id:
        accounts-group-id: t1_demo1
        transactions-group-id: t1_demo2
        transactional-result-id: t1_demo4
      max-poll-records: 10
      session-timeout-ms: 10000
      heartbeat-interval-ms: 3000
    topic:
      create_new_accounts: t1_demo_accounts
      create_new_transactions: t1_demo_transactions
      transactional-result: t1_demo_transaction_result
    producer:
      topic:
        metrics: t1_demo_metrics
        transaction-accept: t1_demo_transaction_accept





