
spring:
  jackson:
    date-format: "yyyy-MM-dd'T'HH:mm:ss"
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: demo-consumer-group
      auto-offset-reset: earliest
      enable-auto-commit: true
    topic:
      transaction_result: t1_demo_transaction_result
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8081

transaction:
  limit: 5
  interval: 1
