spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/t1_transaction_processing
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: transaction-accept-group
      auto-offset-reset: earliest
    topics:
      transaction-accept: "t1_demo_transaction_accept"
      transaction-result: "t1_demo_transaction_result"
app:
  transaction:
    limit: 5  # Количество транзакций (N)
    interval: 7200  # Интервал времени в секундах (T)