spring:
  application:
    name: demo
  redis:
    connection:
      factory:
        host: localhost
        port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        spring.json.add.type.headers: false

logging:
  level:
    ROOT: INFO
    ru.t1.java.demo.controller.ClientController: DEBUG
server:
  port: 8081
kafka:
  topic:
    account: t1_demo_accounts
    transaction: t1_demo_transactions
    transactionAccept: t1_demo_transaction_accept
    transactionResult: t1_demo_transaction_result
  group:
    accounts: group_accounts
    transactions: group_transactions

transactions:
  periodSeconds: 30
  maxTransactions: 3