spring:
  application:
    name: t1-java-demo
  datasource:
    url: "jdbc:postgresql://localhost:5432/t1_demo"
    username: "postgres"
    password: "password"
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml

  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    ROOT: INFO
    ru.t1.java.demo.controller.ClientController: DEBUG

t1:
  scan-path: ru.t1.java.demo
  kafka:
    bootstrap:
      server: ${KAFKA_SERVER:localhost:9092}
    consumer:
      group-id: t1-demo
      group-id-account: account-group
      group-id-transaction: transaction-group
      group-id-transaction-result: demo-consumer-group

    producer:
      enable: true
    topic:
      metrics: t1_demo_metrics
      accounts: t1_demo_accounts
      transactions: t1_demo_transactions
      transaction-accept: t1_demo_transaction_accept
      transaction_result: t1_demo_transaction_result
server:
  port: 8080




